<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2HI8SK2" failures="1" tests="4" name="FourTest" time="40.799" errors="0" timestamp="2024-02-15T23:44:04 IST">
  <testcase classname="tests.FourTest" name="testFour" time="12.114">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.FourTest.testFour(FourTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testFour -->
  <testcase classname="tests.TwoTest" name="testTwo" time="4.937"/>
  <testcase classname="tests.LoginTest" name="login" time="4.992"/>
  <testcase classname="tests.ThreeTest" name="testThree" time="10.006"/>
</testsuite> <!-- FourTest -->
